spring.application.name=SpringSecEx
server.port=81

#spring.security.user.name=jitu
#spring.security.user.password=123

spring.datasource.url=jdbc:mysql://localhost:3306/learningspringsecurity
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
